### ISSUE TITLE
Bug theme when specify path

### ISSUE THREAD

**Issue by AntoninoBonanno** [semantic-release/wordpress#120]
### Current behavior
hi @seebeen, 

I generate my theme files inside the **dist** folder and I want the version to be replaced in this folder and then proceed to create the .zip file.

![image](https://github.com/semantic-release/wordpress/assets/56137431/8a48af89-1e63-4bf4-9d0c-3778a5996050)

So i use this configuration 

```javascript
[
    "@semantic-release/wordpress",
    {
        "type": "theme",
        "slug" : "my-theme",
        "withReadme": true,
        "copyFiles": false,
        "releasePath": "/tmp/wp-release",
        "path": "./dist/"
    }
],
```

the verification step is successful but when the version replacement is carried out I get an error.

I think the file is not found because in `verify-theme.ts` the path is concatenated with the slug

https://github.com/semantic-release/wordpress/blob/2e63d93bdd87e8f58f5d1479bedc8b6a533dcfe9/lib/utils/verify-theme.ts#L9

however in `prepare.ts` the path is not concatenated with the slug

https://github.com/semantic-release/wordpress/blob/2e63d93bdd87e8f58f5d1479bedc8b6a533dcfe9/lib/prepare.ts#L28

My `style.css` is correct

```css
/*
Theme Name: My Theme
Theme URI: https://gitlab.com....
Author: Antonino Bonanno
Version: 0.0.0
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Tags: my-theme
Text Domain: my-theme
Requires at least: 6.3
Tested up to: 6.3.0
Requires PHP: 8.1
*/
```

### Expected behavior

The version is replaced and the zip is passed through a specific path

### `semantic-release` version

22.0.5

### CI environment

GitLab

### Plugins used

"@semantic-release/wordpress": "^1.5.3", 
"@semantic-release/changelog": "^6.0.3",
"@semantic-release/git": "^10.0.1",
"@semantic-release/gitlab": "^12.0.6",

### `semantic-release` configuration

```javascript
[
    "@semantic-release/wordpress",
    {
        "type": "theme",
        "slug" : "my-theme",
        "withReadme": true,
        "copyFiles": false,
        "releasePath": "/tmp/wp-release",
        "path": "./dist/"
    }
],
```

### CI logs

```
[11:30:50 PM] [semantic-release] › ✘  EFILEINVALID File is invalid: style.css
The file is invalid: style.css.
AggregateError
    at prepare (file:///builds/my-theme/theme/node_modules/@semantic-release/wordpress/dist/prepare.js:28:15)
    at async validator (file:///builds//my-theme/theme/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file:///builds//my-theme/theme/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async Promise.all (index 0)
    at async next (file:///builds//my-theme/theme/node_modules/semantic-release/node_modules/p-reduce/index.js:15:44) {
  [errors]: [
    SemanticReleaseError: File is invalid: style.css
        at getError (file:///builds//my-theme/theme/node_modules/@semantic-release/wordpress/dist/utils/get-error.js:5:12)
        at replaceVersions (file:///builds//my-theme/theme/node_modules/@semantic-release/wordpress/dist/utils/replace-versions.js:20:25)
        at async prepare (file:///builds//my-theme/theme/node_modules/@semantic-release/wordpress/dist/prepare.js:26:21)
        at async validator (file:///builds//my-theme/theme/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
        at async file:///builds//my-theme/theme/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
        at async Promise.all (index 0)
        at async next (file:///builds//my-theme/theme/node_modules/semantic-release/node_modules/p-reduce/index.js:15:44) {
      code: 'EFILEINVALID',
      details: 'The file is invalid: style.css.',
      semanticRelease: true,
      pluginName: '@semantic-release/wordpress'
    }
  ]
}
```

**Comment by AntoninoBonanno** [comment]
In tests the paths are not consistent:

https://github.com/semantic-release/wordpress/blob/2e63d93bdd87e8f58f5d1479bedc8b6a533dcfe9/test/1-verify-theme.spec.ts#L76

https://github.com/semantic-release/wordpress/blob/2e63d93bdd87e8f58f5d1479bedc8b6a533dcfe9/test/2-prepare-theme.spec.ts#L94

**Comment by seebeen** [comment]
Good catch 💪

I'll sort it out ASAP.

**Comment by AntoninoBonanno** [comment]
Hi, thanks for the immediate response.
I did a test but with this configuration the file verification fails.

```
[
    "@semantic-release/wordpress",
    {
        "type": "theme",
        "slug" : "my-theme",
        "withReadme": true,
        "copyFiles": false,
        "releasePath": "/tmp/wp-release",
        "path": "./dist/my-theme"
    }
],
```

i think because inside `verify-theme.ts` concat path with slug.

https://github.com/semantic-release/wordpress/blob/2e63d93bdd87e8f58f5d1479bedc8b6a533dcfe9/lib/utils/verify-theme.ts#L9

So the path in verify state is "./dist/my-theme/my-theme" and in prepare state is "./dist/my-theme"

In my case the correct path is "./dist/my-theme".

```
[5:13:15 PM] [semantic-release] › ✘  ETHEMEFILENOTFOUND Your theme must contain these files: style.css, functions.php
Check if the files exist, and if not create them: style.css, functions.php.
AggregateError: 
    SemanticReleaseError: Your theme must contain these files: style.css, functions.php
        at getError (file:///builds/my-theme/theme/node_modules/@semantic-release/wordpress/dist/utils/get-error.js:5:12)
        at verifyTheme (file:///builds/my-theme/theme/node_modules/@semantic-release/wordpress/dist/utils/verify-theme.js:13:13)
        at async verifyConditions (file:///builds/my-theme/theme/node_modules/@semantic-release/wordpress/dist/verify-conditions.js:12:17)
        at async validator (file:///builds/my-theme/theme/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
        at async file:///builds/my-theme/theme/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
        at async Promise.all (index 0)
        at async next (file:///builds/my-theme/theme/node_modules/semantic-release/node_modules/p-reduce/index.js:15:44)
    at file:///builds/my-theme/theme/node_modules/semantic-release/lib/plugins/pipeline.js:55:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async pluginsConfigAccumulator.<computed> [as verifyConditions] (file:///builds/my-theme/theme/node_modules/semantic-release/lib/plugins/index.js:87:11)
    at async run (file:///builds/my-theme/theme/node_modules/semantic-release/index.js:106:3)
    at async Module.default (file:///builds/my-theme/theme/node_modules/semantic-release/index.js:275:22)
    at async default (file:///builds/my-theme/theme/node_modules/semantic-release/cli.js:55:5) {
  errors: [
    SemanticReleaseError: Your theme must contain these files: style.css, functions.php
        at getError (file:///builds/my-theme/theme/node_modules/@semantic-release/wordpress/dist/utils/get-error.js:5:12)
        at verifyTheme (file:///builds/my-theme/theme/node_modules/@semantic-release/wordpress/dist/utils/verify-theme.js:13:13)
        at async verifyConditions (file:///builds/my-theme/theme/node_modules/@semantic-release/wordpress/dist/verify-conditions.js:12:17)
        at async validator (file:///builds/my-theme/theme/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
        at async file:///builds/my-theme/theme/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
        at async Promise.all (index 0)
        at async next (file:///builds/my-theme/theme/node_modules/semantic-release/node_modules/p-reduce/index.js:15:44) {
      code: 'ETHEMEFILENOTFOUND',
      details: 'Check if the files exist, and if not create them: style.css, functions.php.',
      semanticRelease: true,
      pluginName: '@semantic-release/wordpress'
    }
  ]
```
