### ISSUE TITLE
Failure to Complete Creating Package - TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by timnolte** [semantic-release/wordpress#168]
### Current behavior

I'm getting the following results.

```
An error occurred while running semantic-release: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Module.join (node:path:1171:7)
    at success (file:///node_modules/@semantic-release/[secure]/dist/success.js:6:26)
    at validator (file:///node_modules/semantic-release/lib/plugins/normalize.js:36:30)
    at file:///node_modules/semantic-release/lib/plugins/pipeline.js:38:42
    at next (file:///node_modules/semantic-release/node_modules/p-reduce/index.js:16:10) {
  code: 'ERR_INVALID_ARG_TYPE',
  pluginName: '@semantic-release/[secure]'
}
AggregateError: 
    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
        at success (file:///node_modules/@semantic-release/[secure]/dist/success.js:6:26)
        at validator (file:///node_modules/semantic-release/lib/plugins/normalize.js:36:30)
        at file:///node_modules/semantic-release/lib/plugins/pipeline.js:38:42
        at next (file:///node_modules/semantic-release/node_modules/p-reduce/index.js:16:10)
    at file:///node_modules/semantic-release/lib/plugins/pipeline.js:55:13
    at async pluginsConfigAccumulator.<computed> [as success] (file:///node_modules/semantic-release/lib/plugins/index.js:87:11)
    at async run (file:///node_modules/semantic-release/index.js:215:3)
    at async Module.default (file:///node_modules/semantic-release/index.js:275:22)
    at async default (file:///node_modules/semantic-release/cli.js:55:5) {
  errors: [
    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
        at new NodeError (node:internal/errors:405:5)
        at validateString (node:internal/validators:162:11)
        at Module.join (node:path:1171:7)
        at success (file:///node_modules/@semantic-release/[secure]/dist/success.js:6:26)
        at validator (file:///node_modules/semantic-release/lib/plugins/normalize.js:36:30)
        at file:///node_modules/semantic-release/lib/plugins/pipeline.js:38:42
        at next (file:///node_modules/semantic-release/node_modules/p-reduce/index.js:16:10) {
      code: 'ERR_INVALID_ARG_TYPE',
      pluginName: '@semantic-release/[secure]'
    }
  ]
}
```

### Expected behavior

The release package is completed successfully.

### `semantic-release` version

"semantic-release": "^22.0.8", "@semantic-release/wordpress": "^1.5.4"

### CI environment

Buildkite/Local

### `semantic-release` configuration

```json
{
	"branches": [
		{
			"name": "main",
			"channel": "main"
		},
		{
			"name": "develop",
			"prerelease": "rc"
		},
		{
			"name": "feature/Build-Release-Tooling",
			"prerelease": "beta"
		}
	],
	"ci": false,
	"tagFormat": "${version}",
	"plugins": [
		"@semantic-release/commit-analyzer",
		"@semantic-release/release-notes-generator",
		[
			"@semantic-release/changelog",
			{
				"changelogFile": "CHANGELOG.md",
				"changelogTitle": "# Change Log"
			}
		],
		[
			"@semantic-release/exec",
			{
				"prepareCmd": "npm run build"
			}
		],
		[
			"@semantic-release/git",
			{
				"assets": [
					"CHANGELOG.md"
				]
			}
		],
		[
			"@semantic-release/wordpress",
			{
				"type": "theme",
				"slug": "internal-theme-name",
				"withAssets": false,
				"withReadme": true,
				"withVersionFile": true,
				"include": [
					"build"
				],
				"versionFiles": [
					"style.css"
				]
			}
		]
	],
	"preset": "conventionalcommits",
	"publishConfig": {
		"access": "restricted"
	}
}
```

### CI logs

```
[9:55:14 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/exec"
[9:55:14 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[9:55:14 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 1 file(s) to commit
[9:55:16 PM] [semantic-release] [@semantic-release/git] › ℹ  Prepared Git release: 0.2.0-beta.1
[9:55:16 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/git"
[9:55:16 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[9:55:16 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[9:55:16 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/exec"
[9:55:16 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/exec"
[9:55:16 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/[secure]"
[9:55:16 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/[secure]"
[9:55:18 PM] [semantic-release] › ✔  Created tag 0.2.0-beta.1
[9:55:18 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/exec"
[9:55:18 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/exec"
[9:55:18 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/[secure]"
[9:55:18 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/[secure]"
[9:55:18 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/exec"
[9:55:18 PM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/exec"
[9:55:18 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/[secure]"
[9:55:18 PM] [semantic-release] › ✘  Failed step "success" of plugin "@semantic-release/[secure]"
[9:55:18 PM] [semantic-release] › ✘  An error occurred while running semantic-release: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

**Comment by seebeen** [comment]
@AntoninoBonanno is working on a PR. Will be fixed ASAP :)

**Comment by seebeen** [comment]
PR was merged. Can you try the latest version?
